### PR TITLE
Pass the ingress object, not the function to renew

### PR DESCRIPTION
**Pull request by carsonoid**
This fixes auto-renewal of certificates and exposes any future errors.

### CODE REVIEW

**Comment by munnerz** [comment]
Nice find. Thanks very much.

@simonswine could you take a quick look at this and merge? Given the issue at hand, I think this warrants a new patch release.

We don't have test cases for renewal, so this was not picked up.

/assign @simonswine

**Comment by carsonoid** [comment]
@simonswine can I get a review on this? Not having auto-renewal working is a big issue for us. :)

**Comment by simonswine** [comment]
Thanks for this fix @carsonoid, my colleague tries to reproduce the problem, verify your fix and finnally get a new version release

**Comment by killianbrackey** [comment]
Thanks for the quick fix @carsonoid.  @simonswine do you anticipate the patch will be merged up soon here? I am able to reproduce @carsonoid's findings and will be building my own image if you are unsure when the patch may be released as I have a couple of certificates that expire in a week or so here 👍 Happy to help reproduce or test as well.

**Comment by JoshVanL** [comment]
Hi @carlossg, I was able to reproduce the problem. Removing the work queue rate limiter and adding your PR changes, kube-lego was auto renewing as expected.

@simonswine @munnerz
/lgtm

**Pull request merged**
