### PR TITLE
whitelist ingress ip source range

### LINKED ISSUE #203: Adding custom annotations to the kube-lego generated ingresses
# Adding custom annotations to the kube-lego generated ingresses

## Problem

In my global nginx-ingress-controller configuration I set the [whitelist-source-range](https://github.com/kubernetes/ingress/blob/master/controllers/nginx/configuration.md#whitelist-source-range) to allow traffic only from specific IPs. 
This means that the kube-lego generated ingress (see below) for the ACME challenge cannot be accessed by let's encrypt. 

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme-challenge-endpoints: "true"
  creationTimestamp: 2017-05-23T10:54:33Z
  generation: 24
  name: kube-lego-nginx
  namespace: kube-lego
  resourceVersion: "11479082"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-lego/ingresses/kube-lego-nginx
  uid: 3497760c-3fa6-11e7-91bb-42010af0017f
spec:
  rules:
  - host: OUR_HOSTNAME
    http:
      paths:
      - backend:
          serviceName: kube-lego-nginx
          servicePort: 8080
        path: /.well-known/acme-challenge
```

## Suggestion

Add a configuration option to kube-lego to allow defining a custom annotation (ingress.kubernetes.io/whitelist-source-range) for the challenge ingress.

### PR DESCRIPTION
**Pull request by gianrubio**
whitelist all ips for acme http challenge path
fix #203

### CODE REVIEW

**Comment by simonswine** [comment]
I think this will break things for cases where we run multiple ingress classes.

Would be great if we could separate PRs. The white listing of the IPs would be good to get in...

**Comment by sigxcpu76** [comment]
Whitelist all is a good thing @gianrubio . Can you separate the PRs as requested?

Another option for whitelisting would be an external watched on lego's ingress rule and patch it with the whitelist annotation whenever it changes (ugly, I know).

**Comment by gianrubio** [comment]
@simonswine done!

**Comment by munnerz** [comment]
@simonswine are we good to merge this now? I'm unable to see the original commit to make a judgement myself! Looks good to me otherwise.

**Comment by Ulexus** [comment]
This definitely broke IPv6, since "0.0.0.0/0" does not match any IPv6 address.  This means all IPv6-sourced addresses are denied.

The problem is that the nginx template [does not allow for multiple whitelist entries](https://github.com/kubernetes/ingress/blob/master/controllers/nginx/rootfs/etc/nginx/template/nginx.tmpl#L297).  Thus, this change change irretrievably breaks IPv6.

**Pull request merged**
