### PR TITLE
Update godeps and k8s method signatures

### PR DESCRIPTION
**Pull request by aledbf**

### CODE REVIEW

**Comment by simonswine** [comment]
Hey @aledbf, thanks for that! I thought about moving to glide and using the 1.5 https://github.com/kubernetes/client-go libraries. Do you think they are ready?

**Comment by simonswine** [comment]
Btw I just pushed my rewrite to get rid of lego and use the acme library instead

**Comment by aledbf** [comment]
> I thought about moving to glide 

Please no if you use k8s packages :(

> Do you think they are ready?

Not yet (too many changes related to versioning)

**Comment by simonswine** [comment]
Ok I am gonna use your update code commit, I am still wrestling with godep to get everything updated

**Pull request closed without merging**
